# Generated by Django 6.0.5 on 2026-05-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_remove_tweet_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tweet_images/')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweets.tweet')),
            ],
        ),
    ]
