# Generated by Django 6.0.5 on 2026-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
